apiVersion: v1
kind: Service
metadata:
  name: smtp-relay
  namespace: mail
  labels:
    app.kubernetes.io/name: postfix-relay
    app.kubernetes.io/component: mail
    app.kubernetes.io/part-of: homelab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postfix-relay
  ports:
    - name: submission
      port: 587
      targetPort: submission
      protocol: TCP
