apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - harbor/application.yaml
  - gitlab/application.yaml
  - gitlab-runner/application.yaml
  - redis/application.yaml
  - postgres/application.yaml
  - minio/application.yaml
  - mail-relay-postfix/application.yaml
