apiVersion: v1
kind: Secret
metadata:
  name: harbor-core-envvars
  namespace: harbor
type: Opaque
stringData:
  CSRF_KEY: "CHANGE_ME_32_CHAR_CSRF_KEY"
  HARBOR_ADMIN_PASSWORD: "CHANGE_ME_HARBOR_ADMIN_PASSWORD"
  POSTGRESQL_PASSWORD: "CHANGE_ME_POSTGRES_PASSWORD"
  REGISTRY_CREDENTIAL_USERNAME: "harbor_registry_user"
  REGISTRY_CREDENTIAL_PASSWORD: "CHANGE_ME_REGISTRY_PASSWORD"
  _REDIS_URL_CORE: "redis://:CHANGE_ME_REDIS_PASSWORD@redis-master.redis.svc:6379/0"
  _REDIS_URL_REG: "redis://:CHANGE_ME_REDIS_PASSWORD@redis-master.redis.svc:6379/2"
