apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-auth
  namespace: psql
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: "CHANGE_ME_PGADMIN_EMAIL"
  PGADMIN_DEFAULT_PASSWORD: "CHANGE_ME_PGADMIN_PASSWORD"
