apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mail-relay-postfix
  namespace: argo-cd
  labels:
    app.kubernetes.io/name: mail-relay-postfix
    app.kubernetes.io/part-of: homelab
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/BolgovID/k3s-homelab-infra.git
    targetRevision: main
    path: apps/mail-relay-postfix
  destination:
    server: https://kubernetes.default.svc
    namespace: mail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
