apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-apps
  namespace: argo-cd
  labels:
    app.kubernetes.io/name: homelab-apps
    app.kubernetes.io/part-of: homelab
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      name: harbor
      namespace: argo-cd
      jsonPointers:
        - /spec/source/helm/values
  source:
    repoURL: https://github.com/BolgovID/k3s-homelab-infra.git
    targetRevision: main
    path: apps/argocd-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
