apiVersion: v1
kind: Secret
metadata:
  name: dev-gitlab-runner
  namespace: gitlab
type: Opaque
stringData:
  runner-registration-token: ""
  runner-token: "CHANGE_ME_GITLAB_RUNNER_AUTH_TOKEN"
  accesskey: "CHANGE_ME_S3_ACCESS_KEY"
  secretkey: "CHANGE_ME_S3_SECRET_KEY"
