apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: gitlab
type: Opaque
stringData:
  connection: |
    provider: AWS
    region: us-east-1
    host: minio.xulihaxlab.org
    endpoint: http://minio.minio.svc:9000
    path_style: true
    aws_access_key_id: CHANGE_ME_GITLAB_MINIO_ACCESS_KEY
    aws_secret_access_key: CHANGE_ME_GITLAB_MINIO_SECRET_KEY
