apiVersion: v1
kind: Secret
metadata:
  name: postfix-relay-auth
  namespace: mail
type: Opaque
stringData:
  RELAYHOST: "[smtp.gmail.com]:587"
  RELAYHOST_USERNAME: "CHANGE_ME_SMTP_USERNAME"
  RELAYHOST_PASSWORD: "CHANGE_ME_SMTP_PASSWORD"
